### PR TITLE
feat(lang)!: adding localization for the mod

### PR DESCRIPTION
**Pull request by CUexter**
self- explanatory. now use mp_localize for the text that will be displayed to the user

### CODE REVIEW

**Comment by V-rtualized** [comment]
This is great, but we should probably have fallbacks for all the localizations, for the user and for readability

**Comment by CUexter** [comment]
you want it to be bundled with the code ? It's ok I actually did that first

**Comment by CUexter** [comment]
@V-rtualized done

**Review by V-rtualized — APPROVED** [review]
We should probably make some changes to localization and the UI code to allow for better translations (turn separated strings into arrays maybe?) in the future, but I think this is good for now

**Pull request merged**
